openapi: 3.0.3
info:
  title: EatThis Server API
  version: 1.0.11
servers:
  - url: http://localhost:3000
tags:
  - name: dummy
    description: dummyApi Tag

paths:
  /user/signup:
    post:
      tags:
        - user
      summary: User Signup
      description: User 회원가입 API
      requestBody:
        description: User Signup Request Body
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                password:
                  type: string
                nickname:
                  type: string
                gender:
                  type: string
                birth:
                  type: string
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid ID supplied
        '404':
          description: Data not found 
components:
  schemas:
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
        result:
          type: object
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT